exe_path = "$CFS/m4114/FerroX_executables/main3d.gnu.MPI.CUDA.ex"
nersc_project = "m4114"

#[param.alpha]
#min = -2500000000.0
#max = -20003066498.75
#step = nan
#
#[param.beta]
#min = 53390648910.0
#max = 127700394702.00002
#step = nan
#
#[param.gamma]
#min = 121399509900.0
#max = 218758960124.99997
#step = nan

[param.L_z_SC]
min = nan
max = nan
step = 1.0e-9

[param.L_z_DE]
min = 1.0e-9
max = 8.0e-9
step = 1.0e-9

[param.L_z_FE]
min = 1.0e-9
max = 20.0e-9
step = 1.0e-9

[param.L_x]
min = 7.0e-9
max = 100.0e-9
step = 1.0e-9

[param.L_y]
min = 7.0e-9
max = 100.0e-9
step = 1.0e-9

[param.g11]
min = nan
max = nan
step = nan

[param.g44]
min = nan
max = nan
step = nan
